
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package traductores;

/** CUP generated interface containing symbol constants. */
public interface BasicSym {
  /* terminals */
  public static final int INPUT = 16;
  public static final int ELSE = 9;
  public static final int THEN = 8;
  public static final int CHAR = 29;
  public static final int BOOLBINOP = 25;
  public static final int COMP = 24;
  public static final int LOOP = 14;
  public static final int NOT = 18;
  public static final int IDENTIFIER = 30;
  public static final int CONCAT = 28;
  public static final int IF = 7;
  public static final int STRING_LITERAL = 31;
  public static final int DO = 13;
  public static final int PR = 4;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int PL = 3;
  public static final int NUMBINOP = 23;
  public static final int CONST = 22;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int BR = 6;
  public static final int LET = 21;
  public static final int ASSIGN = 19;
  public static final int UNTIL = 15;
  public static final int INTEGER_LITERAL = 26;
  public static final int BL = 5;
  public static final int FLOAT_LITERAL = 27;
  public static final int FOR = 10;
  public static final int TO = 11;
  public static final int LABEL = 20;
  public static final int NEXT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "PL",
  "PR",
  "BL",
  "BR",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "TO",
  "NEXT",
  "DO",
  "LOOP",
  "UNTIL",
  "INPUT",
  "PRINT",
  "NOT",
  "ASSIGN",
  "LABEL",
  "LET",
  "CONST",
  "NUMBINOP",
  "COMP",
  "BOOLBINOP",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "CONCAT",
  "CHAR",
  "IDENTIFIER",
  "STRING_LITERAL"
  };
}

